name: mc886-t2
channels:
  - defaults
  - conda-forge
dependencies:
  - opencv
  - pip
  - python
  - ipython
  - jupyter

  - pip:
    - numpy
    - scipy
    - pandas
    - seaborn
    - matplotlib
    - scikit-learn
