name: mc886-t3
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python
  - opencv
  - ipython
  - jupyter
  - pytorch
  - tqdm
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
